Lesson17: Make carousel with z-index
groovywave/JS_Practice pull request #49
Opened 2023-08-22 15:51 UTC by groovywave

# [Issue No.17](https://github.com/kenmori/handsonFrontend/blob/master/work/markup/17.md#)
- よくあるスライドショーを作ってみましょう。
- 
## [CodeSandBox](https://codesandbox.io/s/github/groovywave/JS_Practice/tree/lesson16/lesson16)<br>

 仕様は

- 仕様
- 画面遷移してから3秒後に解決されるPromiseが返すオブジェクトを元にimgタグを5つつくる。
[以前使ったmy jsonを使う](https://myjson.dit.upm.es/)
- それぞれは.z-indexで重ねた状態。矢印画像をクリックを押すとスライド画像が変わる。
- 5枚中何枚目かを表示して、5/5の場合Nextの矢印はdisabledにする。1/5枚の時はBackボタンはdisabledにする。

今回の対応内容
- 画面遷移してから3秒後に解決されるPromiseが返すオブジェクトを元にimgタグを5つつくる。
- それぞれは.z-indexで重ねた状態。矢印画像をクリックを押すとスライド画像が変わる。
- 5/5の場合Nextの矢印はdisabledにする。1/5枚の時はBackボタンはdisabledにする。

未実装部分
- 5枚中何枚目かを表示

2023-08-22 16:25 UTC, groovywave commented on lesson17/main.js
> +  currentSlide.parentNode.querySelector(".current").classList.remove("current");
.currentは現段階では他に利用していません。
slideの番号表示（5枚中何枚目かを表示）する機能を実装する際に利用予定です。

2023-08-22 16:38 UTC, groovywave commented on lesson17/main.js
> +    slide.style.zIndex = (slideZIndex + 1) % slides.length;
5枚のスライドのz-indexの初期値を
4,3,2,1,0
としました。
ボタンをクリックしたとき、
それぞれに1を足しスライド枚数5で割り、
5/5,4/5,3/5,2/5,1/5
その余りをとって
0,4,3,2,1
とする操作をしています。

2023-08-22 16:49 UTC, groovywave commented on lesson17/main.js
> +  currentSlide.classList.add("current");
.currentは現段階では他に利用していません。
slideの番号表示（5枚中何枚目かを表示）する機能を実装する際に利用予定です。

2023-08-23 11:54 UTC, sae-github requested changes

2023-08-23 11:54 UTC, sae-github commented on lesson17/main.js
> +function renderData(images) {
IMO
I think you are implementing a slider rather than rendering data

2023-08-23 11:54 UTC, sae-github commented on lesson17/main.js
> +  const carousel = document.createElement("section");
Q. Is there any reason to use the section tag?
Section tags would require a heading, with a few exceptions

> The <section> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a generic standalone section of a document, which doesn't have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.

[ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)

2023-08-23 11:54 UTC, sae-github commented on lesson17/main.js
> +  for (const [index, image] of images.entries()) {
IMO
Since images is an array, I thought forEach would be sufficient.

```suggestion
  images.forEach((image, index) => {
```

2023-08-23 11:54 UTC, sae-github commented on lesson17/main.js
> +
IMO
I think we can isolate it to a function

2023-08-23 11:54 UTC, sae-github commented on lesson17/main.js
> +  fragment.appendChild(prevButton);
nits
```suggestion
fragment.appendChild(nextButton).appendChild(nextIcon);
```

2023-08-23 11:54 UTC, sae-github commented on lesson17/main.js
> +  const currentSlide = getCurrentSlide(slides);
Q.` js-current`を使用して取得することはできませんか？

2023-08-23 11:54 UTC, sae-github commented on lesson17/main.js
> +    document.getElementById("next").classList.add("js-hidden");
IMO
It would be nice to use the [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) attribute

2023-08-23 20:29 UTC, groovywave commented on lesson17/main.js
> +function renderData(images) {
Thank you sae-san :）
I fixed that.
71496733758a52022ca5df060377f5b90434d23d
Actually I changed to makeSlide.

2023-08-23 20:31 UTC, groovywave commented on lesson17/main.js
> +  const carousel = document.createElement("section");
Thank you sae-san :)
I learned about section.
83cc86b917c6f302a2c9954fa662d96b0c61b62b
(I put it that for dividing from tabs and articles in later lesson.)

2023-08-23 20:32 UTC, groovywave commented on lesson17/main.js
> +  for (const [index, image] of images.entries()) {
Thank you sae-san :)
It's simple.
98f3a5ac66be45b3376e44b815dcf4fb77591ba8

2023-08-23 20:33 UTC, groovywave commented on lesson17/main.js
> +
Thank you sae-san :)
It's easy to read.
01bcf90f37cd73cf96ad2300eb551eb5f0bf4c7b

2023-08-23 20:33 UTC, groovywave commented on lesson17/main.js
> +  fragment.appendChild(prevButton);
Thank you sae-san :)
ef982655d16ff671b9e5abbcf054aed41c11c793

2023-08-23 20:35 UTC, groovywave commented on lesson17/main.js
> +  const currentSlide = getCurrentSlide(slides);
Thank you sae-san :)
I used let currentIndex.
93c90af308d55ec9aee5096b417ec17576628c7a
5236fb32662b53db8f6742833cc40c7a6c472915

2023-08-24 12:31 UTC, sae-github commented on lesson17/main.js
> +    slide.className = "js-slide-img";
IMO
`js**` prefixes are better used for elements used in JavaScript.
I believe this className is only used in style.css

2023-08-24 12:34 UTC, sae-github commented on lesson17/main.js
> +    document.getElementById("next").classList.add("js-hidden");
classNameではなく属性値[disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) を使用するという意味です！

2023-08-24 12:38 UTC, sae-github commented on lesson17/css/style.css
> +.js-slides-container {
Q. How do you distinguish between using id and not using id?

2023-08-24 16:13 UTC, groovywave commented on lesson17/css/style.css
> +.js-slides-container {
https://qiita.com/ari-chel/items/b06c68aec8849d0409dd

2023-08-24 21:56 UTC, groovywave commented on lesson17/main.js
> +    slide.style.zIndex = (slideZIndex + 1) % slides.length;
Thank you sae san  :)
I use .js-current,
It's simple.
7aa93134b728c395d4170ecd205e521f9a8999b2

2023-08-24 21:57 UTC, groovywave commented on lesson17/main.js
> +    slide.className = "js-slide-img";
Thank you sae san :)
I leaned about prefix!
ef9787331b231eb47077debc7bf3e81ebe76c11e

2023-08-24 22:07 UTC, sae-github commented on lesson17/css/style.css
> +.js-slides-container {
classを使用してスタイリングする時とidを使用する時の違いを質問したつもりでした
わかりづらくてすみません🙇🏻‍♀️

2023-08-24 22:10 UTC, sae-github commented on lesson17/main.js
> +  nextButton.className = "next";
IMO
I think it is a unique element used in js, so it is better to specify an id and get it with getElementById.
If style.css also requires it, I think it is better to specify a separate className.

ex)
```
nextButton.id = "js-**";
nextButton.className = "":

```

2023-08-24 22:14 UTC, sae-github commented on lesson17/main.js
> +  console.log(slides[currentIndex]);
MUST
Unnecessary code

2023-08-24 22:15 UTC, sae-github commented on lesson17/main.js
> +    });
IMO
I think this location mimics communication with the server, so adding loading would improve the user experience.

2023-08-25 10:56 UTC, groovywave commented on lesson17/css/style.css
> +.js-slides-container {
> classを使用してスタイリングする時とidを使用する時の違いを質問したつもりでした わかりづらくてすみません🙇🏻‍♀️
こちらこそ、申し訳ありません。
さえさんの意図するところは理解していたのですが、ネット情報に振り回されてしまいました(^^;

2023-08-25 11:36 UTC, groovywave commented on lesson17/main.js
> +    });
Thank you ssae-san:)
I add loading circle.
4c1cd5d154ffb2943e7189ebca5a7e8de65f53ab

2023-08-25 11:37 UTC, groovywave commented on lesson17/main.js
> +  console.log(slides[currentIndex]);
I'm sorry...
5f064489365f4b92ee6432a83d9c532f7ce72d8a

2023-08-25 11:39 UTC, groovywave commented on lesson17/main.js
> +  nextButton.className = "next";
Thank you sae-san:)
I learned basic skill!!
You taught me a lot of things!!
f7e2ea889bd824e8b3bf87671e14eddd7788f76d

2023-08-25 12:31 UTC, haru-programming reviewed
Q. Has anything been tested and failed?
![Screenshot by Dropbox Capture](https://github.com/groovywave/JS_Practice/assets/67426438/7397e7f3-fb0e-437c-9c85-37c3240c7be2)

2023-08-25 14:34 UTC, groovywave commented
> Q. Has anything been tested and failed? ![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/67426438/263269273-7397e7f3-fb0e-437c-9c85-37c3240c7be2.png)

I use codacy but ignored 

> Q. Has anything been tested and failed? ![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/67426438/263269273-7397e7f3-fb0e-437c-9c85-37c3240c7be2.png)

I use codacy that checks my code.
https://www.codacy.com/
It picks minor issues and I ignore that :<

2023-08-25 14:35 UTC, groovywave commented
> Q. Has anything been tested and failed? ![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/67426438/263269273-7397e7f3-fb0e-437c-9c85-37c3240c7be2.png)

I use codacy that checks my code.
https://www.codacy.com/
It picks minor issues and I ignore that :<

2023-08-25 21:57 UTC, kenmori commented on lesson17/css/style.css
> +}
IMO
細かいですけれど、slideに関するものはslide.cssみたいな感じで分けてもいいかもしれないです

2023-08-25 21:57 UTC, kenmori commented on lesson17/img/loading-circle.gif:Zone.Identifier
> +HostUrl=https://github.com/
なんですかこれ...

2023-08-25 21:58 UTC, kenmori commented on lesson17/main.js
> +const slides = [];
一応、代入可能とはいえ、letにしますか？immutableに見えます

2023-08-26 01:57 UTC, sae-github commented on lesson17/main.js
> +  slides[currentIndex].classList.add("js-current");
IMO
`js-current`も複数の要素に指定する想定はないと思うのでidで指定するといいかと思います

2023-08-26 01:58 UTC, sae-github commented on lesson17/main.js
> +  }
IMO

```suggestion
    if (currentIndex === 0) {
    document.getElementById("js-prev").disabled = true;
  }
  if (currentIndex === slides.length - 1) {
    document.getElementById("js-next").disabled = true;
  }
```

2023-08-26 13:31 UTC, haru-programming commented
@groovywave 

> I use codacy that checks my code.
https://www.codacy.com/
It picks minor issues and I ignore that :<

codacyというCIツールがあるのですね！
教えていただきありがとうございます。
ツールのことが理解できていないのですが、ignoreしたい旨設定をして
checkはpassした状態にした方が良い気がしました。

2023-08-26 14:58 UTC, groovywave commented
> @groovywave
> 
> > I use codacy that checks my code.
> > https://www.codacy.com/
> > It picks minor issues and I ignore that :<
> 
> codacyというCIツールがあるのですね！ 教えていただきありがとうございます。 ツールやignoreしたい内容を把握できていないのですが、ツール側で ignoreしたい旨設定をして checkはpassした状態にした方が良い気がしました🙏

使いこなしていないのでuninstallしました^^;
cssのモダンな書き方や、
コードの脆弱性診断までしてくれたので、
使いこなせれば有用なツールだなとは思いました^^

2023-08-26 14:59 UTC, groovywave commented on lesson17/main.js
> +  }
Thank you sae-san :)
I fixed that.
b16c34a914e29c99e7d0592cc1b1945e9d0c8858

2023-08-26 14:59 UTC, groovywave commented on lesson17/main.js
> +  slides[currentIndex].classList.add("js-current");
Thank you sae-san :)
I learned about using id!!
39e1604c504b8b6687f91798c6f03219da03e903

2023-08-26 15:02 UTC, groovywave commented on lesson17/main.js
> +const slides = [];
Thank you ken-san :)
this makes sense.
b213f49b6104f432d66d4d3cdea2a9472e26be9e

2023-08-26 15:05 UTC, groovywave commented on lesson17/img/loading-circle.gif:Zone.Identifier
> +HostUrl=https://github.com/
It was made by itself when I pasted loading-circle.gif :<
c563e7f32a9380079fa20af5df4c88928f244413

2023-08-26 15:05 UTC, groovywave commented on lesson17/css/style.css
> +}
Thank you ken-san :)
f5922d87e68d00dc89e38c524f17c4601e0af6e2

2023-08-26 23:24 UTC, haru-programming approved these changes

2023-08-26 23:25 UTC, haru-programming commented
自分の指摘箇所はApproveさせていただきました！

2023-08-26 23:45 UTC, sae-github approved these changes

2023-08-27 07:09 UTC, merged